version: "3.8"
services:
  frontend:
    container_name: Fuksipassi-Frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8000:3000"
    networks:
      fuksipassi:
        ipv4_address: 10.10.1.2
    depends_on:
      - directus
    restart: unless-stopped

  db:
    container_name: Fuksipassi-PostgreSQL
    image: postgres:15-alpine
    volumes:
      - directus_data_prod:/var/lib/postgresql/data
    networks:
      fuksipassi:
        ipv4_address: 10.10.1.3
    env_file:
      - .env.prod.db
    restart: unless-stopped

  directus:
    container_name: Directus
    image: directus/directus:10.8.2
    ports:
      - "8001:8055"
    volumes:
      - directus_data_prod:/directus/database
      - directus_uploads_prod:/directus/uploads
      - directus_extensions_prod:/directus/extensions
    networks:
      fuksipassi:
        ipv4_address: 10.10.1.4
    depends_on:
      - db
    env_file:
      - .env.prod
    restart: unless-stopped

volumes:
  directus_data_prod:
  directus_uploads_prod:
  directus_extensions_prod:

networks:
  fuksipassi:
    driver: bridge
    name: "fuksipassi"
    ipam:
      config:
        - subnet: 10.10.1.0/16
          gateway: 10.10.1.1
