name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set environment variables
        run: |
          cat ${{ secrets.PROD }} > .env.prod
          cat ${{ secrets.PROD_DB }} > .env.prod.db
      - name: Clone another repository
        uses: actions/checkout@v4
        with:
          repository: serveriry/fuksipassi
          ref: main

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            git pull
            sh ./directus/backup.sh
            docker-compose -f compose.yaml down
            docker-compose -f compose.yaml up -d --build
            cd ./directus
            sh import.sh
            cd ..
