name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
#      - name: Set environment variables
#        run: |
#          cp example.env.prod .env.prod
#          cp example.env.prod.db .env.prod.db
#      - name: Build and test
#        run: |
#          docker-compose -f compose.yaml build
#          cd directus
#          sh import.sh
#          cd ..
#          docker-compose -f compose.yaml up -d
#          docker-compose -f compose.yaml down
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set environment variables
        run: |
          cat ${{ secrets.PROD }} > .env.prod
          cat ${{ secrets.PROD_DB }} > .env.prod.db
      - name: Build
        run: |
          docker-compose -f compose.yaml build
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker compose -f compose.yaml down
            docker compose -f compose.yaml up -d
            
